name: Koloseum

on:
  schedule:
    - cron: '*/10 * * * *'     
  workflow_dispatch:      # ręczne uruchomienie z GitHub UI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright requests

      - name: Install Playwright browsers and dependencies
        run: |
          playwright install --with-deps chromium

      - name: Run Colosseum Ticket Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python Koloseum.py
