name: Otomoto

on:
  schedule:
    - cron: '0 8 * * *'  # → 11:00 CET
    - cron: '0 17 * * *'  # → 20:00 CET      # co godzinę od 8:00 do 22:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python otomoto.py

      - name: Commit IDs
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add otomoto.txt
          git commit -m "update ids" || echo "no changes"
          git push
